use_frameworks!

target 'LLLTestLibrary_Example' do
  pod 'LLLTestLibrary', :path => '../'

  target 'LLLTestLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
